pipeline {
  agent any

  stages {
    stage('Terraform Apply') {
      steps {
        dir('terraform') {
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }

    stage('Ansible Deployment') {
      steps {
        dir('ansible') {
          sh 'ansible-playbook -i inventory playbook.yml'
        }
      }
    }
  }
}
